<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Сервис баннеров
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bannerGet
     *
     * Получение всех баннеров c фильтрацией по фиче и/или тегу.
     *
     */
    public function testBannerGet()
    {
    }

    /**
     * Test case for bannerIdDelete
     *
     * Удаление баннера по идентификатору.
     *
     */
    public function testBannerIdDelete()
    {
    }

    /**
     * Test case for bannerIdPatch
     *
     * Обновление содержимого баннера.
     *
     */
    public function testBannerIdPatch()
    {
    }

    /**
     * Test case for bannerPost
     *
     * Создание нового баннера.
     *
     */
    public function testBannerPost()
    {
    }

    /**
     * Test case for userBannerGet
     *
     * Получение баннера для пользователя.
     *
     */
    public function testUserBannerGet()
    {
    }
}
